### ISSUE TITLE
Ability to delete location

### ISSUE THREAD

**Issue by aaronspindler** [aaronspindler/Team.Bio#129]

**Comment by NguyenTuanAnh2195** [comment]
Hi @aaronspindler , I think I can implement this feature. Can I take this task ?

**Comment by NguyenTuanAnh2195** [comment]
Hi @aaronspindler , I figured that in the future there would be many elements that need to be deleted, I took the liberty of adding flowbite.js - a tailwindcss plugin of sort to make it easier to handle common elements, such as modals. I've also refactored the delete team modal to use this new tool. Please provide feedback at your earliest convenience, thank you.
