### ISSUE TITLE
Ability to delete team

### ISSUE THREAD

**Issue by aaronspindler** [aaronspindler/Team.Bio#130]

**Comment by NguyenTuanAnh2195** [comment]
HI, I'm starting open source contribution. This seems like a good place to start. Can I take this task ?

**Comment by aaronspindler** [comment]
> HI, I'm starting open source contribution. This seems like a good place to start. Can I take this task ?

Go ahead! What I envision for this is a link on the company settings page that allows the user to delete a team.

**Comment by NguyenTuanAnh2195** [comment]
> 

Hi, I'm having a few issues and questions.
1. This piece of code:
`"OPTIONS": {
            "CONNECTION_POOL_KWARGS": {"ssl_cert_reqs": None},
        },`
in the file `settings.py` is causing issues on my side when logging in. I think this is not an option of `django.core.cache.backends.redis.RedisCache` but rather of `django_redis.cache.RedisCache` ?

2. I'm missing some of the essential AWS and GOOGLE api keys. Can you send me those or should I provision them on my own ? 
3. When the user delete a non-existent team, what should we do ? 
4. Do you think that we need a sort of confirmation modal before deleting a team ?

**Comment by aaronspindler** [comment]
Hey, I will look into 1, for now just remove the line for your development branch.

2. I do not want to share api keys, and since these services offer free tiers you should be able to make an account and not have to pay anything.
3. If the user tries to delete a non-existent or non-owned team, throw a 404
4. I think a confirmation modal would be a good idea

**Comment by NguyenTuanAnh2195** [comment]
Hi @aaronspindler I've added the required function here in this PR: https://github.com/aaronspindler/Team.Bio/pull/186
I can't seem to link it to this issue. Could you check it out and give me some feedback ? Thanks.
