### ISSUE TITLE
Error uploading `.heic` image

### ISSUE THREAD

**Issue by inventhouse** [aaronspindler/Team.Bio#281]
**Describe the bug**
Uploading a [High Efficiency Image File Format](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) image (`.heic`), for example as a profile image, causes an error claiming that it is either not an image file or is corrupted.

**To Reproduce**
1. Go to your profile and click "Edit Profile"
2. Under "Photo" click on "Choose File"
3. Select a `.heic` image
4. Save profile; see error in screenshot

**Expected behavior**
Should set my photo to the desired image.

**Screenshots**

<img width="583" alt="image" src="https://github.com/aaronspindler/Team.Bio/assets/17170027/acb6599e-84df-4a0e-9cff-fdb17a1af7e7">

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 (a) (22E772610a)
 - Browser: Safari
 - Version: 16.4 (18615.1.26.110.1)

**Comment by aaronspindler** [comment]
Fixed by: https://github.com/aaronspindler/Team.Bio/pull/283
